import NxWelcome from './nx-welcome';
import * as React from 'react';
import {
  RouterProvider,
  createRouter,
  createRootRoute,
  createFileRoute,
  Outlet,
  Link,
} from '@tanstack/react-router';

// This is a generated file. Please do not edit this file directly.
const homeRoute = createFileRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: Home,
});

function Home() {
  return (
    <div>
      This is the generated root route.{' '}
      <Link to="/page-2">Click here for page 2.</Link>
    </div>
  );
}

const page2Route = createFileRoute({
  getParentRoute: () => rootRoute,
  path: '/page-2',
  component: Page2,
});

function Page2() {
  return (
    <div>
      <Link to="/">Click here to go back to root page.</Link>
    </div>
  );
}

const rootRoute = createRootRoute({
  component: () => (
    <div>
      <NxWelcome title="bunki" />
      <br />
      <hr />
      <br />
      <div role="navigation">
        <ul>
          <li>
            <Link to="/">Home</Link>
          </li>
          <li>
            <Link to="/page-2">Page 2</Link>
          </li>
        </ul>
      </div>
      <Outlet />
    </div>
  ),
});

const routeTree = rootRoute.addChildren([homeRoute, page2Route]);
const router = createRouter({ routeTree });

export function App() {
  return <RouterProvider router={router} />;
}

export default App;
